/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Motivation = IDL.Record({ 'message' : IDL.Text });
export const Question = IDL.Record({
  'correctIndex' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMotivation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'getAllMotivations' : IDL.Func([], [IDL.Vec(Motivation)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getRandomMotivation' : IDL.Func([], [IDL.Text], []),
  'isAnswerCorrect' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Motivation = IDL.Record({ 'message' : IDL.Text });
  const Question = IDL.Record({
    'correctIndex' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
  });
  
  return IDL.Service({
    'addMotivation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addQuestion' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [], []),
    'getAllMotivations' : IDL.Func([], [IDL.Vec(Motivation)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getRandomMotivation' : IDL.Func([], [IDL.Text], []),
    'isAnswerCorrect' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };