/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Motivation { 'message' : string }
export interface Question {
  'correctIndex' : bigint,
  'answers' : Array<string>,
  'text' : string,
}
export interface _SERVICE {
  'addMotivation' : ActorMethod<[string], bigint>,
  'addQuestion' : ActorMethod<[string, Array<string>, bigint], undefined>,
  'getAllMotivations' : ActorMethod<[], Array<Motivation>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getRandomMotivation' : ActorMethod<[], string>,
  'isAnswerCorrect' : ActorMethod<[bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];